### DISCUSSION TITLE
Simpler Docker Compose: Only Run PrivacyIDEA and DB

### DISCUSSION THREAD

**Discussion by mattv8** [gpappsoft/privacyidea-docker#16] [Q&A] [answered]
I'm trying to make just a dumbed down compose.yml to start this stack so I can roll my own reverse proxy, which I feel like should be pretty straightforward. However I'm missing something here, because when it starts up, privacyidea refuses to connect to the db. Any tips? Is this possible?
```
services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_MYSQL_LOCALHOST_USER: true
    expose:
      - ${DB_PORT}
    volumes:
      - mysql:/var/lib/mysql:rw,Z
    networks:
      - privacyidea
    restart: always
  privacyidea:
    image: gpappsoft/privacyidea-docker:${PI_VERSION}
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 10s
        window: 60s
    expose:
      - ${PI_PORT}
    volumes:
      - pidata:/privacyidea/etc/persistent:rw,Z
      - type: bind
        source: scripts/
        target: /privacyidea/scripts/
        read_only: true
      - type: bind
        source: templates/resolver.json
        target: /privacyidea/etc/persistent/resolver.json
        read_only: true
    networks:
      - privacyidea
    healthcheck:
      test:
        - CMD
        - /privacyidea/healthcheck.py
      start_period: 30s
      start_interval: 10s
      interval: 8s
      timeout: 10s
      retries: 3
    depends_on:
      - db
    restart: always
volumes:
  mysql: {}
  pidata: {}
networks:
  privacyidea: {}
```

My `.env` isn't anything special so I'm not going to include it here. I added a healthcheck on the db server because I assume the issue is mysql is trying to run entrypoints, but pi always starts before it's complete.

It seems like the error stems from the pi entrypoint not being able to access a config file?
```
privacyidea-1  | Traceback (most recent call last):
privacyidea-1  |   File "/privacyidea/entrypoint.py", line 14, in <module>
privacyidea-1  |     app = create_app(config_name='production',config_file='/privacyidea/etc/pi.cfg')
privacyidea-1  |   File "/privacyidea/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
privacyidea-1  |     return self.dbapi.connect(*cargs, **cparams)
privacyidea-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privacyidea-1  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```

**Comment by mattv8** [comment, marked as answer]
I just figured it out... It was more challenging than I thought. I've updated my docker-compose.yml to include all the necessary env vars. I also needed to create a mysql entrypoint to grant privileges to `$DB_USER`.
1. Clone this repo into your working directory
```
git clone https://github.com/gpappsoft/privacyidea-docker.git privacyidea-docker
cd privacyidea-docker
```

2. Copy the prod .env:
```
cp environment/application-prod.env .env
``` 

3. create **scripts/init_db.sql**:
```
GRANT ALL PRIVILEGES ON `${DB_NAME}`.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;
```

4. Update the **docker-compose.yml**:
```
services:
  privacyidea:
    image: gpappsoft/privacyidea-docker:${PI_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PI_ADMIN: ${PI_ADMIN}
        PI_ADMIN_PASS: ${PI_ADMIN_PASS}
        SUPERUSER_REALM: ${SUPERUSER_REALM}
        PI_LOGLEVEL: ${PI_LOGLEVEL}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_EXTRA_PARAMS: ${DB_EXTRA_PARAMS}
        DB_API: ${DB_API}
    environment:
      PI_BOOTSTRAP: true
    env_file:
      - .env
    ports:
      - "${PI_PORT}:${PI_PORT}"
    volumes:
      - pidata:/privacyidea/etc/persistent:rw,Z
      - ./scripts/:/privacyidea/scripts/:ro
      - ./templates/resolver.json:/privacyidea/etc/persistent/resolver.json:ro
    networks:
      - privacyidea
    depends_on:
      - db
    healthcheck:
      test:
        - CMD
        - /privacyidea/healthcheck.py
      start_period: 10s
      start_interval: 10s
      interval: 12s
      timeout: 10s
      retries: 6
    restart: always
  db:
    image: mariadb:latest
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_MYSQL_LOCALHOST_USER: true
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql:rw,Z
      - ./scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - privacyidea
    restart: always
volumes:
  mysql: {}
  pidata: {}
networks:
  privacyidea: {}
```

5. Build the container using unchanged Dockerfile:
```
docker compose build
```
6. Start the stack as usual:
```
docker compose up
```

I feel like this is generally simpler and less confusing to me, but YMMV. I already have reverse-proxy, RADIUS and LDAP servers running elsewhere, so I didn't need those services.
